"""Initial migration

Revision ID: 3c8ced925918
Revises: 916acde2af8e
Create Date: 2025-05-11 22:02:16.043789

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "3c8ced925918"
down_revision: Union[str, None] = "916acde2af8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
