"""initial migrations

Revision ID: 4a5998c5ef9c
Revises:
Create Date: 2025-05-11 21:46:05.153480

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a5998c5ef9c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("pool_address", sa.String(), nullable=False),
        sa.Column("pair_address", sa.String(), nullable=False),
        sa.Column("liquidity_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("quote_token_address", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pool_address"),
    )
    op.create_index(op.f("ix_pools_id"), "pools", ["id"], unique=False)
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("largest_pool_id", sa.Integer(), nullable=True),
        sa.Column("pool_count", sa.Integer(), nullable=False),
        sa.Column("total_supply", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column(
            "total_liquidity_usd", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["largest_pool_id"],
            ["pools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tokens_address"), "tokens", ["address"], unique=True)
    op.create_index(op.f("ix_tokens_id"), "tokens", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_address"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_pools_id"), table_name="pools")
    op.drop_table("pools")
    # ### end Alembic commands ###
