"""Initial migration

Revision ID: 5de6d04ba49f
Revises: 4a5998c5ef9c
Create Date: 2025-05-11 21:57:26.093198

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "5de6d04ba49f"
down_revision: Union[str, None] = "4a5998c5ef9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
