"""Fix circular FK with use_alter

Revision ID: 916acde2af8e
Revises: 5de6d04ba49f
Create Date: 2025-05-11 22:01:54.113976

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "916acde2af8e"
down_revision: Union[str, None] = "5de6d04ba49f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
